[package]
name = "egzreader"
version = "2.0.1"
authors = ["Akira Mizuno <akmizno@gmail.com>"]
edition = "2018"
description = "Read gzip/non-gzip stream easily."
keywords = ["gzip"]
repository = "https://github.com/akmizno/egzreader"
license = "MIT/Apache-2.0"

[dependencies]
flate2 = "1.0"
