[package]
name = "egzreader"
version = "1.0.1"
authors = ["Akira Mizuno <akmizno@gmail.com>"]
edition = "2018"
description = "A gzip and non-gzip pholymorphic reader."
repository = "https://github.com/akmizno/egzreader"
license = "MIT"

[dependencies]
flate2 = "1.0"
